### ISSUE TITLE
Accessing actual figure image files

### ISSUE THREAD

**Issue by IIZCODEII** [IllDepence/unarXive#16]
Hello,

Is there a way to access to actual figure image files using, for instance, their id ?

```
{'c575cbb5-2504-4327-aa59-d1e6c97c0a53': {'caption': 'Quantum trajectories for harmonic oscillators.In eachcase,the oscillation period,τ=2π/ω=888.57au\\tau =2 \\pi /\\omega =888.57 au.In cases A & D ,m=2000aum=2000 au while in case B,m=200aum =200 au. Case D is a set of classical trajectories (Q=0Q=0)for this system.',
  'type': 'figure'}

```

Thanks !

**Comment by IllDepence** [comment]
Hi,

the IDs, such as `c575cbb5-2504-4327-aa59-d1e6c97c0a53` in your example, are assigned during the dataset generation.

Because unarXive doesn't contain the figures themselves, and in the source data on arXiv they don't have unique IDs, there's no dedicated mapping.

One way to retrieve them might be to

* determine the order of figures in a paper
* get the paper source ([bulk data](https://info.arxiv.org/help/bulk_data/index.html) / [single papers](https://info.arxiv.org/help/ancillary_files.html))
* go through the LaTeX source and for each `\figure{}`
    * cross-check the caption just to be sure
    * retrieve the figure itself, either from a source file referred to by `\includegraphics{}` or from the LaTeX source itself is its done with pgfplots, tikz, etc.

**Comment by IIZCODEII** [comment]
I'll take a look at that ! Thank you !
